name: "CodeTestingCriticFlow"
_target_: flow_modules.aiflows.CodeTestingCriticFlowModule.CodeTestingCritic.instantiate_from_default_config
description: "Tests the generated code and provides feedback."
input_interface:
  - "code"
  - "public_tests_individual_io"
output_interface:
  - "testing_results_summary"
  - "all_tests_passed"
