name: "CodeDebugFlow"
description: "Composite flow for generating and testing code."
max_rounds: 4
early_exit_key: "all_tests_passed"

input_interface:
  - "problem_description"
  - "input_description"
  - "output_description"
  - "io_examples_and_explanation"
  - "public_tests_individual_io"

output_interface:
  - "code"
  - "all_tests_passed"

subflows_config:
  CodeGenerator:
    flow_class_name: flow_modules.aiflows.CodeGeneratorFlow
    flow_endpoint: CodeGenerator
    user_id: local
    _target_: flow_modules.aiflows.CodeGeneratorFlow.instantiate_from_default_config

  CodeTestingCritic:
    flow_class_name: flow_modules.aiflows.CodeTestingCriticFlow
    flow_endpoint: CodeTestingCritic
    user_id: local
    _target_: flow_modules.aiflows.CodeTestingCriticFlow.instantiate_from_default_config
